! Global variables
    
Module Global_Data
    
    integer, parameter :: DOUBLE = SELECTED_REAL_KIND(p=8)
    
    ! Directory with data moments
    CHARACTER(LEN=120), parameter :: dir_mom = 'C:\Users\rd699\Dropbox\TradeDeficitsLabor\data\makeMoments_June2020\output\'
    
    ! Country to be estimated
    integer, parameter :: COUNTRY_EST = 6
   
    ! Indicates the optimization algorithm
    ! ALGORITHM = 1 ==> Nelder-Mead
    ! ALGORITHM = 2 ==> Simulated Annealing
    integer, parameter :: ALGORITHM = 2
    ! Number of sectors
    integer, parameter :: numK      = 6
    ! Number of countries
    integer, parameter :: numC      = 6
    ! Number of parameters in the StartingPoint.csv file
    integer, parameter :: numP      = 127
    ! Number of parameters to be estimated
    integer, parameter :: NP        = numP
    ! Number of fixed parameters fed into the estimation procedure
    integer, parameter :: NP_fixed  = 5

    ! Temperature Simulated Annealing
    real(KIND=DOUBLE), parameter :: TempSimAnn = 0.001
    
    ! Keeps track of function iterations
    integer FUNCTION_ITERATION
    
    ! Value of best objective function so far
    real(KIND=DOUBLE) F_BEST
    
    real(KIND=DOUBLE) big_L_bar(numC,1), lambda, delta, mu(numK,numC), &
                      xsi, zeta, gamma(numK,numC), nu(numK,numK,numC), &
                      beta
    
    real(KIND=DOUBLE) big_U_Guess(numK), big_L_Guess(numK), &
                      x_bar_Guess(numK)
    
    real(KIND=DOUBLE) param_global(NP), scaling_global(NP), lb_global(NP), &
                      ub_global(NP), FixedPar(NP_fixed)
    integer           mask_global_in(NP), mask_global(NP)
    
    real(KIND=DOUBLE), allocatable, dimension(:) :: lb_in(:), ub_in(:)
    
    real(KIND=DOUBLE) big_Y(numK,numC)
    
    real(KIND=DOUBLE) s_tilde_Data(numK+1,numK+1), &
                      pi_Data(numC,numC,numK), &
                      big_Y_Data(numK,numC), &
                      Emp_Data(numK,numC), &
                      ShareEmp_Data(numK,numC), &
                      w_bar_Data(numK,numC), &
                      Unemp_Data(numC,1), &
                      big_L_bar_Data(numC,1), &
                      NX_Data(numC,1), &
                      CoeffVar_w_Data, &
                      Ergodic_Dist_Data(numK+1,1)
    
    ! Structure with different sets of parameters of the model
    type Parameters

        real(KIND=DOUBLE) b(numK,nUmC) 
        real(KIND=DOUBLE) eta(numK,numC) 
        real(KIND=DOUBLE) kappa_tilde(numK,numC)
        real(KIND=DOUBLE) sigma_x(numK,numC)
        real(KIND=DOUBLE) chi(numK,numC)
        real(KIND=DOUBLE) C_US(numK,numK) 
        
    end type
    
    ! Structure with moments generated by the model
    type MomentsOut
        
        real(KIND=DOUBLE) s_tilde(2*numK,2*numK)
        real(KIND=DOUBLE) Emp(numK)
        real(KIND=DOUBLE) ShareEmp(numK)
        real(KIND=DOUBLE) w_bar(numK)
        real(KIND=DOUBLE) Var_w(numK)
        real(KIND=DOUBLE) Unemp
        real(KIND=DOUBLE) labor_share(numK)
        real(KIND=DOUBLE) u(numK)
        real(KIND=DOUBLE) big_L(numK)
        real(KIND=DOUBLE) lambda_tilde(numK)
        real(KIND=DOUBLE) x_bar(numK)
        real(KIND=DOUBLE) w_tilde(numK)
        real(KIND=DOUBLE) q_theta(numK)
        real(KIND=DOUBLE) theta(numK)
        real(KIND=DOUBLE) G_x_bar(numK)
        real(KIND=DOUBLE) dist_out
        
    end type
    
    type SteadyState
        real(KIND=DOUBLE) pi(numC,numC,numK)
        real(KIND=DOUBLE) big_L(numK,numC)
        real(KIND=DOUBLE) x_bar(numK,numC)
        real(KIND=DOUBLE) w_tilde(numK,numC)
        real(KIND=DOUBLE) big_U(numK,numC)
        real(KIND=DOUBLE) big_Y(numK,numC)
    end type
    
    type Shock
        real(KIND=DOUBLE) A_hat(numK,numC)
        real(KIND=DOUBLE) d_hat(numC,numC,numK)
        real(KIND=DOUBLE) NX(numC,1)
    end type
    
end Module Global_Data
    