function set_global_data
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
% Countries to be estimated
global COUNTRY_EST;
COUNTRY_EST = 6;
% Number of sectors
global K;
K = 6;
% Number of countries
global N;
N = 6;
% Number of parameters in the StartingPoint.csv file
global numP;
numP = 127;
% Number of parameters to be estimated
global NP ;
NP = numP;
% Number of fixed parameters fed into the estimation procedure
global NP_fixed;
NP_fixed = 5;

% Temperature Simulated Annealing
global TempSimAnn;
TempSimAnn = 0.001;
% Keeps track of function iterations
global FUNCTION_ITERATION;
FUNCTION_ITERATION = 0;


%%%%%%%%%%
% Read data
%%%%%%%%%%

% Gamma




%%%%%%%%%%
% Structure with moments generated by the model
%%%%%%%%%%

% Transition rate, this format is different from the Fortran code
global s;
s = zeros(K, K, N);

% 1-period transition rates
global s_tilde;
s_tilde = zeros(2*K, 2*K);

% Average wages
global w_bar;
w_bar = zeros(K);

% Variance of wages
global Var_w;
Var_w = zeros(K);

% Labor share
global labor_share;
labor_share = zeros(K);

% Number of workers, measured as the sum of workers who are employed or
%   unemployed and searching within sector k 
%   This is different from the Fortran code, which is a 1-d array big_L(K)
global big_L;
big_L = zeros(K, N);

% The household head’s Lagrange multiplier on the budget constraint
global lambda_tilde;
lambda_tilde = zeros(K);

global x_bar;
global w_tilde;
global q_theta;
global theta;
global G_x_bar;
global dist_out;

end


